/* eslint-disable @next/next/no-html-link-for-pages */
export default function PrivacyPage() {
  return <main className="privacy-page"><article className="privacy-content">
    <a className="privacy-back" href="/">&larr; Torna a Raggi&ograve;</a>
    <h1>Informativa privacy</h1>
    <p className="privacy-updated">Ultimo aggiornamento: 20 settembre 2026</p>
    <section><h2>1. Titolare del trattamento</h2><p>Ciclofficina InControPedale e Bike4City, Via di Casal Bruciato 11, 00159 Roma. Per richieste relative ai dati personali: WhatsApp 351 684 9832.</p></section>
    <section><h2>2. Dati trattati per la diagnosi</h2><p>Il servizio tratta i messaggi della diagnosi e identificatori tecnici pseudonimi necessari al funzionamento e alla sicurezza. Le foto vengono trattate soltanto se selezionate e confermate dall&apos;utente. Non sono richiesti nome, posizione, rubrica o dati sanitari.</p></section>
    <section><h2>3. Finalit&agrave;</h2><p>I dati sono utilizzati per fornire la diagnosi guidata richiesta dall&apos;utente. Le foto vengono inviate solo dopo una scelta esplicita. I controlli tecnici e antifrode proteggono il servizio e gli utenti.</p></section>
    <section><h2>4. Statistiche anonime e aggregate</h2><p>Per comprendere se Raggi&ograve; &egrave; utile e migliorare il servizio vengono conteggiati soltanto: aperture dell&apos;applicazione, diagnosi avviate e completate, utilizzo della funzione foto, indicazioni a rivolgersi alla ciclofficina, clic sul contatto WhatsApp e canale di provenienza dell&apos;accesso, come sito, card, locandina o gazebo.</p><p>Ogni evento incrementa direttamente un contatore giornaliero, mensile e complessivo. Non viene creato un archivio delle attivit&agrave; dei singoli visitatori e non &egrave; possibile ricostruire il comportamento di una determinata persona.</p><p>Ai fini statistici non vengono conservati nomi, recapiti, messaggi, fotografie, indirizzi IP, posizione, dispositivo, browser, identificativi pubblicitari, impronte digitali o identificativi Firebase. Il parametro contenuto negli eventuali QR code indica soltanto il canale di provenienza e non contiene codici personali.</p><p>Raggi&ograve; non utilizza Google Analytics, Firebase Analytics, cookie statistici o altri strumenti destinati a riconoscere e seguire i visitatori. Le statistiche non sono utilizzate per profilazione, pubblicit&agrave; o marketing e non sono cedute a terzi. Poich&eacute; il sistema non installa strumenti statistici sul dispositivo e non legge informazioni gi&agrave; presenti nel dispositivo, non viene richiesto un consenso preventivo per questi conteggi aggregati.</p></section>
    <section><h2>5. Servizi utilizzati</h2><p>Firebase di Google gestisce autenticazione anonima, funzioni cloud e, quando richiesto, le foto. OpenAI elabora i messaggi e le sole foto confermate per produrre la risposta. Le richieste OpenAI usano store: false.</p></section>
    <section><h2>6. Conservazione</h2><p>Le foto remote sono eliminate automaticamente entro 7 giorni. I contatori statistici contengono soltanto valori aggregati e non dati riferibili ai singoli utenti. I dati non sono venduti e non sono utilizzati per pubblicit&agrave;.</p></section>
    <section><h2>7. Fornitori e trasferimenti</h2><p>Google e OpenAI agiscono come fornitori tecnologici e possono trattare dati anche fuori dallo Spazio economico europeo applicando le garanzie previste dai rispettivi accordi e dalla normativa applicabile. I normali dati tecnici necessari alla connessione e alla sicurezza possono essere trattati temporaneamente dai fornitori dell&apos;infrastruttura, ma non vengono inseriti nelle statistiche di Raggi&ograve;. Un contatto tramite WhatsApp &egrave; soggetto anche alle condizioni di WhatsApp.</p></section>
    <section><h2>8. Diritti dell&apos;interessato</h2><p>L&apos;utente pu&ograve; chiedere accesso, rettifica, cancellazione, limitazione, opposizione e portabilit&agrave; quando applicabili. Pu&ograve; inoltre presentare reclamo al Garante per la protezione dei dati personali.</p></section>
    <section><h2>9. Sicurezza e limiti</h2><p>I trasferimenti avvengono tramite connessioni cifrate. Raggi&ograve; fornisce un primo orientamento prudente e non sostituisce il controllo di un meccanico qualificato.</p></section>
  </article></main>;
}